# Generated by Django 5.0 on 2024-08-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('pass_word', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('supplier', 'Supplier'), ('stockkeeper', 'Stockkeeper'), ('admin', 'admin')], default='farmer', max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('sent_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storekeeper_name', models.CharField(blank=True, max_length=100, null=True)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_date_time', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_inventories', to='grain_harverst_app.userstable')),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storekeeper_inventories', to='grain_harverst_app.userstable')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_inventories', to='grain_harverst_app.userstable')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='grain_harverst_app.userstable')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='grain_harverst_app.userstable')),
            ],
        ),
    ]
